name: merced
favicon: null
layout_spectrum: 0.770255187060684
typography_spectrum: 0.5276494733989239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.676855128724128
  lightness: 0.8790940158069134
  saturation: 0.8991441987454891
  rhythmicContrast: 0.354185702977702
purpose: []
